/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StorageSimple } from "./StorageSimple";
export * as factories from "./factories";
export { StorageSimple__factory } from "./factories/StorageSimple__factory";
