/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StorageArrayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addValue"
      | "getContractInfo"
      | "getLength"
      | "getValueAt"
      | "getValues"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ValueAdded"): EventFragment;

  encodeFunctionData(functionFragment: "addValue", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getLength", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getValueAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getValues", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getValueAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getValues", data: BytesLike): Result;
}

export namespace ValueAddedEvent {
  export type InputTuple = [newValue: string, addedBy: AddressLike];
  export type OutputTuple = [newValue: string, addedBy: string];
  export interface OutputObject {
    newValue: string;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorageArray extends BaseContract {
  connect(runner?: ContractRunner | null): StorageArray;
  waitForDeployment(): Promise<this>;

  interface: StorageArrayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addValue: TypedContractMethod<[newValue: string], [void], "nonpayable">;

  getContractInfo: TypedContractMethod<[], [[string, string[]]], "view">;

  getLength: TypedContractMethod<[], [bigint], "view">;

  getValueAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getValues: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addValue"
  ): TypedContractMethod<[newValue: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<[], [[string, string[]]], "view">;
  getFunction(
    nameOrSignature: "getLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValueAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getValues"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "ValueAdded"
  ): TypedContractEvent<
    ValueAddedEvent.InputTuple,
    ValueAddedEvent.OutputTuple,
    ValueAddedEvent.OutputObject
  >;

  filters: {
    "ValueAdded(string,address)": TypedContractEvent<
      ValueAddedEvent.InputTuple,
      ValueAddedEvent.OutputTuple,
      ValueAddedEvent.OutputObject
    >;
    ValueAdded: TypedContractEvent<
      ValueAddedEvent.InputTuple,
      ValueAddedEvent.OutputTuple,
      ValueAddedEvent.OutputObject
    >;
  };
}
