/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StorageArray } from "./StorageArray";
export type { StorageMapping } from "./StorageMapping";
export type { StorageSimple } from "./StorageSimple";
export * as factories from "./factories";
export { StorageArray__factory } from "./factories/StorageArray__factory";
export { StorageMapping__factory } from "./factories/StorageMapping__factory";
export { StorageSimple__factory } from "./factories/StorageSimple__factory";
