/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StorageMappingInterface extends Interface {
  getFunction(
    nameOrSignature: "deleteValue" | "exists" | "getValue" | "setValue"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ValueDeleted" | "ValueSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "exists", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setValue",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setValue", data: BytesLike): Result;
}

export namespace ValueDeletedEvent {
  export type InputTuple = [key: AddressLike, deletedBy: AddressLike];
  export type OutputTuple = [key: string, deletedBy: string];
  export interface OutputObject {
    key: string;
    deletedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueSetEvent {
  export type InputTuple = [
    key: AddressLike,
    value: string,
    changedBy: AddressLike
  ];
  export type OutputTuple = [key: string, value: string, changedBy: string];
  export interface OutputObject {
    key: string;
    value: string;
    changedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorageMapping extends BaseContract {
  connect(runner?: ContractRunner | null): StorageMapping;
  waitForDeployment(): Promise<this>;

  interface: StorageMappingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteValue: TypedContractMethod<[key: AddressLike], [void], "nonpayable">;

  exists: TypedContractMethod<[key: AddressLike], [boolean], "view">;

  getValue: TypedContractMethod<[key: AddressLike], [string], "view">;

  setValue: TypedContractMethod<
    [key: AddressLike, value: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteValue"
  ): TypedContractMethod<[key: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[key: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getValue"
  ): TypedContractMethod<[key: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setValue"
  ): TypedContractMethod<
    [key: AddressLike, value: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ValueDeleted"
  ): TypedContractEvent<
    ValueDeletedEvent.InputTuple,
    ValueDeletedEvent.OutputTuple,
    ValueDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ValueSet"
  ): TypedContractEvent<
    ValueSetEvent.InputTuple,
    ValueSetEvent.OutputTuple,
    ValueSetEvent.OutputObject
  >;

  filters: {
    "ValueDeleted(address,address)": TypedContractEvent<
      ValueDeletedEvent.InputTuple,
      ValueDeletedEvent.OutputTuple,
      ValueDeletedEvent.OutputObject
    >;
    ValueDeleted: TypedContractEvent<
      ValueDeletedEvent.InputTuple,
      ValueDeletedEvent.OutputTuple,
      ValueDeletedEvent.OutputObject
    >;

    "ValueSet(address,string,address)": TypedContractEvent<
      ValueSetEvent.InputTuple,
      ValueSetEvent.OutputTuple,
      ValueSetEvent.OutputObject
    >;
    ValueSet: TypedContractEvent<
      ValueSetEvent.InputTuple,
      ValueSetEvent.OutputTuple,
      ValueSetEvent.OutputObject
    >;
  };
}
