/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StorageArray__factory } from "./StorageArray__factory";
export { StorageMapping__factory } from "./StorageMapping__factory";
export { StorageSimple__factory } from "./StorageSimple__factory";
